[alembic]
script_location = %(here)s/migrations
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s
prepend_sys_path = .
path_separator = os
# sqlalchemy.url is set dynamically from .env in migrations/env.py


[post_write_hooks]
hooks = ruff
ruff.type = exec
ruff.executable = ruff
ruff.options = check --fix --no-cache --ignore=E501,W291 REVISION_SCRIPT_FILENAME
