
# Variables
COMPOSE ?= docker compose
COMPOSE_FILE ?= docker-compose.yaml
SERVICE ?= app
DB_SERVICE ?= database
ENV_FILE ?= .env

## Show help (targets with a "##" comment)
help: ## Show this help
	@echo "Use 'make <target>' where <target> is one of:"; \
	grep -E '^[a-zA-Z0-9._-]+:.*##' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS=": .*## "} {printf "  %-25s %s\n", $$1, $$2}'

start: ## Start services (docker compose up)
	$(COMPOSE) -f $(COMPOSE_FILE) up --remove-orphans

stop: ## Stop services
	$(COMPOSE) -f $(COMPOSE_FILE) down

build: ## Build images with docker compose
	$(COMPOSE) -f $(COMPOSE_FILE) build --parallel

restart: stop start ## Reinicia los servicios

logs: ## Follow logs for the app service
	$(COMPOSE) -f $(COMPOSE_FILE) logs -f $(SERVICE)

shell: ## Open a shell in the app container
	$(COMPOSE) -f $(COMPOSE_FILE) exec $(SERVICE) /bin/bash

db-shell: ## Open psql inside the database container (reads DATABASE_USER/NAME from $(ENV_FILE) if present)
	@if [ -f $(ENV_FILE) ]; then \
		USER=$$(grep -E '^DATABASE_USER=' $(ENV_FILE) | cut -d'=' -f2); \
		DB=$$(grep -E '^DATABASE_NAME=' $(ENV_FILE) | cut -d'=' -f2); \
		echo "Connecting to $$DB as $$USER..."; \
		$(COMPOSE) -f $(COMPOSE_FILE) exec $(DB_SERVICE) psql -U $$USER -d $$DB; \
	else \
		$(COMPOSE) -f $(COMPOSE_FILE) exec $(DB_SERVICE) psql -U $(DATABASE_USER) -d $(DATABASE_NAME); \
	fi

## Migrations
migration-create: ## Create an autogenerated migration (prompts for message)
	@read -p "Enter migration message: " msg; \
	$(COMPOSE) -f $(COMPOSE_FILE) exec $(SERVICE) alembic revision --autogenerate -m "$$msg"

migration-create-empty: ## Create an empty migration (prompts for message)
	@read -p "Enter migration message: " msg; \
	$(COMPOSE) -f $(COMPOSE_FILE) exec $(SERVICE) alembic revision -m "$$msg"

migration-upgrade: ## Apply migrations (upgrade head)
	$(COMPOSE) -f $(COMPOSE_FILE) exec $(SERVICE) alembic upgrade head

migration-downgrade: ## Revert the last migration (downgrade -1)
	$(COMPOSE) -f $(COMPOSE_FILE) exec $(SERVICE) alembic downgrade -1

migration-history: ## Show migration history
	$(COMPOSE) -f $(COMPOSE_FILE) exec $(SERVICE) alembic history

migration-current: ## Show current migration
	$(COMPOSE) -f $(COMPOSE_FILE) exec $(SERVICE) alembic current

migration-show: ## Show the head migration
	$(COMPOSE) -f $(COMPOSE_FILE) exec $(SERVICE) alembic show head

migration-sql: ## Generate SQL for upgrade head
	$(COMPOSE) -f $(COMPOSE_FILE) exec $(SERVICE) alembic upgrade head --sql

## Desarrollo: install / format / lint / test / clean
install: ## Install/sync dependencies (uses `uv sync` if available)
	@command -v uv >/dev/null 2>&1 && uv sync || (echo "uv not found. Install it."; exit 1)

fmt: ## Format code with ruff
	@command -v ruff >/dev/null 2>&1 && ruff format src tests || true

lint: ## Run lint with ruff
	@command -v ruff >/dev/null 2>&1 && ruff check src tests --fix || true

test: ## Run tests with pytest
	@command -v pytest >/dev/null 2>&1 && pytest -q || true

all: install fmt lint test ## Run all dev tasks

clean: ## Clean pyc files and caches
	@find . -name '__pycache__' -type d -exec rm -rf {} + || true
	@find . -name '*.pyc' -delete || true

.PHONY: help start stop build restart logs shell db-shell migration-create migration-create-empty migration-upgrade migration-downgrade migration-history migration-current migration-show migration-sql all install fmt lint test clean
